version: '3.8'

services:
  # Redis: Auth
  redis-auth:
    image: redis:7
    container_name: redis-auth
    ports:
      - "10680:6379"
    command: redis-server --appendonly yes
    networks:
      - redisnet

  # Redis: Cache
  redis-cache:
    image: redis:7
    container_name: redis-cache
    ports:
      - "10681:6379"
    command: redis-server
    networks:
      - redisnet

  # Redis: Pub/Sub
  redis-pubsub:
    image: redis:7
    container_name: redis-pubsub
    ports:
      - "10682:6379"
    command: redis-server
    networks:
      - redisnet

  # MongoDB
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "10717:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - mongonet

  # PostgreSQL
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: jennifer
      POSTGRES_PASSWORD: jennifer123
      POSTGRES_DB: jenniferdb
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "10532:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pgnet

  # Zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - kafkanet

  # Kafka
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:10092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      - kafkanet

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "10572:5672"
      - "11572:15672"
    networks:
      - rabbitnet

  # Ollama (LLM inference with GPU)
  # ollama:
    # image: ollama/ollama
    # container_name: ollama
    # ports:
      # - "11434:11434"
    # volumes:
      # - ollama_data:/root/.ollama
    # networks:
      # - ollamanet

  # # Ollama WebUI
  # ollama-webui:
    # image: ghcr.io/open-webui/open-webui:main
    # container_name: ollama-webui
    # depends_on:
      # - ollama
    # environment:
      # - OLLAMA_BASE_URL=http://ollama:11434
    # ports:
      # - "13000:8080"
    # volumes:
      # - ollama_webui_data:/app/backend/data
    # networks:
      # - ollamanet

volumes:
  mongo_data:
  postgres_data:
  ollama_data:
  ollama_webui_data:

networks:
  redisnet:
  kafkanet:
  rabbitnet:
  mongonet:
  pgnet:
  ollamanet:
